# Generated by Django 2.2.2 on 2019-07-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_postgamestats_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='version',
            field=models.CharField(default='9.13.1', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BannedChampions',
        ),
    ]
