# Generated by Django 2.2.2 on 2019-07-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bot_commands'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='close_bets_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
